### PR TITLE
udpates world class

### PR DESCRIPTION
**Pull request by tapickell**
Adds more of the API functionality to the class
Removes chat function that should exist in it's own class

### CODE REVIEW

**Comment by nhajratw** [comment]
hi @tapickell -  I just returned from vacation and noticed you closed all your pull requests. Was there some issue with them?

**Comment by tapickell** [comment]
Yeah, I thought about it and the changes would really require a larger
request and a version bump. I am going to work on more smaller bits locally
and then do one larger PR to your repo when it is all ready if that's cool.

**Comment by tapickell** [comment]
Also quick question, what / how are you running test suite? Was not sure if
minitest or rspec was being used. I thought about putting this into circle
ci but looks like would have to have a mc/bukkit server run on the test
instance. Doable but a little more work to setup.

**Comment by nhajratw** [comment]
Honestly, I have no idea. I wrote this 7 years ago. I’ll try to figure it out this week sometime.
---
Nayan Hajratwala - 734.658.6032 - http://agileshrugged.com - @nhajratw

**Comment by tapickell** [comment]
Lol, ok cool. If not I can just add a setup for one or the other. I have no
preference I don't do Ruby anymore only using it for teaching OOP

**Comment by nhajratw** [comment]
much appreciated :)

**Pull request closed without merging**
